# Generated by Django 4.0.10 on 2024-05-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='request',
            new_name='servicerequest',
        ),
    ]
