# Generated by Django 4.0.10 on 2024-06-08 11:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 8, 11, 3, 7, 809378, tzinfo=utc)),
        ),
    ]
